# Generated by Django 3.2 on 2023-01-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_order',
            field=models.BooleanField(default='True'),
        ),
    ]
