# Generated by Django 3.2 on 2023-01-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
