# Generated by Django 3.2 on 2023-01-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_wishlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
