# Generated by Django 3.2 on 2023-01-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='order',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
