# Generated by Django 3.2 on 2023-01-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20230121_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='We will respond to this address.', max_length=254, verbose_name='Your Email Address'),
        ),
    ]
