# Generated by Django 3.2 on 2023-01-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
    ]
