# Generated by Django 3.2 on 2023-01-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admin_responded',
            field=models.BooleanField(default='False'),
        ),
    ]
