# Generated by Django 3.2 on 2023-01-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_contact_admin_responded'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This name will be displayed as the author on the published review.', max_length=50, verbose_name='Your Name')),
                ('title', models.CharField(help_text='What is the title of your review?', max_length=64, verbose_name='Review Title')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Your rating out of 5 stars', verbose_name='Rate Us')),
                ('body', models.TextField(help_text='Write your review here', max_length=1064, verbose_name='Your Review')),
                ('admin_approved', models.BooleanField(default='False')),
            ],
            options={
                'verbose_name_plural': 'Site Rewiew',
            },
        ),
    ]
