# Generated by Django 3.2 on 2023-01-24 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_subscribeemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribeemail',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='subscribeemail',
            name='email',
            field=models.EmailField(help_text='We will respond to this address.', max_length=254, unique=True, verbose_name='Your Email Address'),
        ),
    ]
