# Generated by Django 3.2 on 2023-01-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20230124_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=models.TextField(max_length=1064, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Your Email Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(max_length=64, verbose_name='Message Subject'),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='body',
            field=models.TextField(max_length=1064, verbose_name='Your Review'),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Your Name'),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rate Us'),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Review Title'),
        ),
    ]
