# Generated by Django 3.2 on 2023-01-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230118_1906'),
        ('checkout', '0005_alter_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.books'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='material_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.posters'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
