# Generated by Django 3.2 on 2023-01-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230118_1906'),
        ('checkout', '0006_auto_20230120_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='book',
            field=models.ForeignKey(blank=True, default='N/A', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.books'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='material_size',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='poster',
            field=models.ForeignKey(blank=True, default='N/A', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.posters'),
        ),
    ]
