# Generated by Django 3.2 on 2023-01-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
