# Generated by Django 3.2 on 2023-01-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230111_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='slug',
        ),
        migrations.AddField(
            model_name='books',
            name='product_code',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('product_code', models.CharField(blank=True, max_length=19, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.genre')),
            ],
            options={
                'verbose_name_plural': 'Posters',
            },
        ),
    ]
