# Generated by Django 3.2 on 2023-01-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230118_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='product_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='posters',
            old_name='product_code',
            new_name='code',
        ),
    ]
