# Generated by Django 3.2 on 2023-01-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230128_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posters',
            name='image_url',
        ),
    ]
